[package]
name = "oxybar"
version = "0.1.0"
authors = ["Kim Desrosiers <kimdesro@gmail.com>"]

[dependencies]
relm = "^0.14.0"
relm-derive = "^0.14.0"
glib = "^0.5.0"
gtk = "^0.4.0"
sys-info = "*"

[dependencies.gdk]
version = "0.8.0"
features = ["v3_22"]